### ISSUE TITLE
error in X1 Nano

### ISSUE THREAD

**Issue by faffa42** [xmm7360/xmm7360-pci#114]
Hi trying to run it on a brand new Thinkpad Nano, but I get this error
`~/tmp/xmm7360-pci$ sudo python3 rpc/open_xdatachannel.py --apn internet.wind
Traceback (most recent call last):
  File "rpc/open_xdatachannel.py", line 42, in <module>
    r = rpc.XMMRPC()
  File "/home/faffa/tmp/xmm7360-pci/rpc/rpc.py", line 19, in __init__
    self.fp = os.open(path, os.O_RDWR | os.O_SYNC)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/xmm0/rpc'
`
On Ubuntu 20.04, any idea?

**Comment by t11c** [comment]
I had a similiar error on Ubuntu 21.04,  disconnecting any wifi networks solved it for me.

**Comment by tgxn** [comment]
I've also seen this error after suspend/resume cycle as in #1.

Please try:
- Ensure WiFi Is disabled.
- Unload module + restart system
- make/make load driver, test connection.

**Comment by tgxn** [comment]
X1 Nano also reported working here: https://github.com/xmm7360/xmm7360-pci/issues/125
