### ISSUE TITLE
Unable to install on fedora since it doesn't have build-essential support?

### ISSUE THREAD

**Issue by joecucu** [xmm7360/xmm7360-pci#147]
Hello, is there an alternate route to get this installed in place of build-essential?
When I Try to install it I get "No match for argument: build-essential"

Edit: I was able to get this installed via yum, but I am now receiving this error if anyone has any idea on how to proceed.

```
[user@sys-net xmm7360-pci]$ sudo python3 rpc/open_xdatachannel.py
Traceback (most recent call last):
  File "rpc/open_xdatachannel.py", line 42, in <module>
    r = rpc.XMMRPC()
  File "/home/user/tmp/xmm7360-pci/rpc/rpc.py", line 19, in __init__
    self.fp = os.open(path, os.O_RDWR | os.O_SYNC)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/xmm0/rpc'
[user@sys-net xmm7360-pci]$ 

```

**Comment by tgxn** [comment]
This indicates that the device isn't mounted on `/dev/xmm0/rpc` - Hav eyou run `make` and `make load` ?

You would need to advise which OS you are running, as build-essential can be different on different flavors of Linux.
`build-essential` includes all the dependencies in order to run the `make ` and `make load`.

Try searching google for something like "build-essential <YOUR_OS>"
