### ISSUE TITLE
It partially works on x1 carbon gen8 with archlinux 6.2.9

### ISSUE THREAD

**Issue by yummy527** [xmm7360/xmm7360-pci#204]
Hi,guys. 
Finally, it works after struggling. Here I just give some steps to reproduce how to make it work.

# machine and OS
machine: Lenovo X1 carbon gen8
OS: archlinux with kernel 6.2.9
Python: 3.10(I am not sure whether it maters or not.)

# steps to reproduce successful work
step 1: After a **fresh reboot**, just "remove" or blacklist the iosm drive with command: 
```shell
sudo rmmod iosm
```
**This step is important!** If iosm is not removed, it will `block` the xmm7360-pci drive and you will the warning like "insert a sim card to use this modem".

*This command above will not delete iosm from your disk. Every time you boot your machine, the iosm will be there because it is in the kernel. You can check it with command `lspci -k` and if you carefully check the output, you will find iosm there.*

step 2: Install ModemManager
If you are using ArchLinux as me,
```shell
sudo pacman -S modemmanager
```
If you are using Ubuntu, 
```shell
sudo apt-get update
sudo apt-get -y install modemmanager
```
If other OS, just find the right way to install ModemManager.

step 3: edit  `xmm7360.ini`
Open the file `xmm7360.ini`, and make sure to
- set your apn. (I am not sure yet, but it seems that wrong apn will also work. You can select APN in the setting pannel later.) 
- **uncomment `dbus=True`**

Here is mine:
```txt
# driver config
apn="ctnet"

#ip-fetch-timeout=1
#nodefaultroute=True
#metric=1000

# uncomment to not add DNS values to /etc/resolv.conf
#noresolv=True

# used to activate NetworkManager integration
dbus=True

# Setup script config
BIN_DIR=/usr/local/bin

```
step 4: execute the script `lte.sh`
```shell
cd ~/Downloads/xmm7360-pci # cd to where your downloaded folder `xmm7360-pci` is.
sudo ./scripts/lte.sh setup
```
That's all for the script. Command `lte up` is not needed here.

# Others
I find this working method somewhat occasionally. The "giving up" error stops me for more than half a year (cry...). In these several days, I just wonder whether the LTE or 4G could work or not on my Linux laptop.

After searching and trying many pages on the web, finally I find this one works.

If the **Mobile Network** in the system setting panel just tells you "**insert a sim card to use this modem**" even if you have already insert you card. The trick is: repeat step 2 and step 4. That is reinstall ModemManager and run `lte.sh` script again.

If the **Mobile Network** in the system setting panel disappears(yes it may disappear when you running the lte.sh), as well reinstall ModemManager and run `lte.sh` script again. 

```shell
sudo pacman -S modemmanager
cd ~/Downloads/xmm7360-pci # cd to where your downloaded folder `xmm7360-pci` is.
sudo ./scripts/lte.sh setup
```
I have no idea why merely trying `sudo ./scripts/lte.sh setup` does not work. But **reinstalling modemmanager and then running the script WORKS.**

That's all my finding. Hope it works for you. 
![image](https://user-images.githubusercontent.com/9738778/230634943-0bd18d1f-c741-4789-9392-b4a49a108bcb.png)

It is a little strange that the signal shows very weak, 0%. But downloading and uploading works. 

I am excited that it finally works. If finding other `techniques` later, I will share here.

**Comment by dieselburner** [comment]
> The trick is to repeat step 2 and step 4. That is to reinstall ModemManager and run lte.sh script again.

No. That's not how open source supposed to work.

**Comment by yummy527** [comment]
> > The trick is to repeat step 2 and step 4. That is to reinstall ModemManager and run lte.sh script again.
> 
> No. That's not how open source supposed to work.

Apologize. Reinstalling ModemManager is not needed at all.

**Comment by rafaelrsanches** [comment]
My output of `lspci -k` on Fedora looks like this:

`05:00.0 Wireless controller [0d40]: Intel Corporation XMM7360 LTE Advanced Modem (rev 01)
	Subsystem: Intel Corporation Device 0020
	Kernel modules: iosm, xmm7360`

**Comment by yummy527** [comment]
> My output of `lspci -k` on Fedora looks like this:
> 
> 
> 
> ```
> 
> 05:00.0 Wireless controller [0d40]: Intel Corporation XMM7360 LTE Advanced Modem (rev 01)
> 
> 	Subsystem: Intel Corporation Device 0020
> 
> 	Kernel modules: iosm, xmm7360
> 
> ```
> 
> 
> 
> 

In your case, it seems that iosm is "removed" and xmm7360 is installed but not used.

cd to the downloaded xmm7360 folder, and try step 4. That is my suggestion.

**Comment by rafaelrsanches** [comment]
> > My output of `lspci -k` on Fedora looks like this:
> > ```
> > 
> > 05:00.0 Wireless controller [0d40]: Intel Corporation XMM7360 LTE Advanced Modem (rev 01)
> > 
> > 	Subsystem: Intel Corporation Device 0020
> > 
> > 	Kernel modules: iosm, xmm7360
> > ```
> 
> In your case, it seems that iosm is "removed" and xmm7360 is installed but not used.
> 
> cd to the downloaded xmm7360 folder, and try step 4. That is my suggestion.

I'm able to do step 4, but the Kernel module doesn't go to "Kernel driver in use:". And if I run `sudo lte up` I got the following error:
```
lte.sh: manage xmm7360-pci
APN: myapn.com
Script: /home/user/xmm7360-pci/scripts/lte.sh; Link: /usr/local/bin

bringing wwan0 up!
Traceback (most recent call last):
  File "/home/user/xmm7360-pci/scripts/../rpc/open_xdatachannel.py", line 42, in <module>
    r = rpc.XMMRPC()
        ^^^^^^^^^^^^
  File "/home/user/xmm7360-pci/rpc/rpc.py", line 19, in __init__
    self.fp = os.open(path, os.O_RDWR | os.O_SYNC)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/xmm0/rpc'
Cannot find device "wwan0"
``

**Comment by rafaelrsanches** [comment]
I was able to get it working on Fedora 38 (with Secure Boot disabled), but I have 2 questions.

1. You need to do this steps every time you reboot?
2. Is it possible to do this with Secure Boot enabled?

**Comment by tgxn** [comment]
I merged the rmmod ioctl thing today, should fix this.

**Comment by KataFF** [comment]
I tried the steps described in the OP, but it did not work for me (see #209)

**Comment by vebodev** [comment]
yummy527, 

I did the same instructions on Archlinux. However I met a different case not mentioned before.
![image](https://github.com/xmm7360/xmm7360-pci/assets/63761915/3f7c37e4-8306-4e7e-b74b-4a5f0eea5f07)
It is not the same UI as yours. I have no idea to find out the same config as yours.

Please advice what should I do. thank you

**Comment by yummy527** [comment]
> yummy527,
> 
> I did the same instructions on Archlinux. However I met a different case not mentioned before. ![image](https://private-user-images.githubusercontent.com/63761915/284144583-3f7c37e4-8306-4e7e-b74b-4a5f0eea5f07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjI2NjEsIm5iZiI6MTcwNjA2MjM2MSwicGF0aCI6Ii82Mzc2MTkxNS8yODQxNDQ1ODMtM2Y3YzM3ZTQtODMwNi00ZTdlLWI3NGItNGE1ZjBlZWE1ZjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyMTI0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMWE1MDk2YTBmYjhhNzMzZTllNTM2NGJjM2U2NDMwZTdhMzI3MDgyNjEzYTI2YjQ0MGU3MmMzYjk3YzQxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RmkxsHG-CjbMlrsTyiT5yr8SqSDh8Te3AqlrkEIIbZI) It is not the same UI as yours. I have no idea to find out the same config as yours.
> 
> Please advice what should I do. thank you

As far I could remember,  it just worked after second `sudo ./scripts/lte.sh setup`. I changed nothing related to user name and password in your screenshot, just using the default ones. Be sure to set your APN in `xmm7360.ini`. Since you are using China Telecom, just `apn="ctnet"`.

PS: Long time no use this xmm7360 tool. Today I tried to run it, and just found that it didn't work now.

**Comment by SimPilotAdamT** [comment]
I seem to have some success... I [forked this project](https://github.com/SimPilotAdamT/xmm7360-pci-SPAT) and managed to get it compiling after some fiddling, and the module works. My only remaining issue is integration with ModemManager, which seems to fail on my device... I am using a ThinkaPad P52s with `lspci` output:
```
03:00.0 Wireless controller [0d40]: Intel Corporation XMM7360 LTE Advanced Modem [8086:7360] (rev 01)
        Subsystem: Intel Corporation XMM7360 LTE Advanced Modem [8086:0020]
        Flags: bus master, fast devsel, latency 0, IRQ 150
        Memory at dd200000 (64-bit, non-prefetchable) [size=4K]
        Memory at dd201000 (64-bit, non-prefetchable) [size=1K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable+ Count=1/4 Maskable- 64bit+
        Capabilities: [70] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [148] Latency Tolerance Reporting
        Capabilities: [150] L1 PM Substates
        Kernel driver in use: xmm7360
        Kernel modules: iosm
```
I am using Arch Linux with the latest Arch kernel in the stable repos. Having followed the steps in your original post, ModemManager refuses to pick up my module (I have to use the `lte` commands instead), spitting these into the journald log:
```
Feb 22 15:25:26 adam-arch-laptop systemd[1]: Starting Modem Manager...
Feb 22 15:25:26 adam-arch-laptop ModemManager[7776]: <msg> ModemManager (version 1.22.0-1) starting in system bus...
Feb 22 15:25:26 adam-arch-laptop systemd[1]: Started Modem Manager.
Feb 22 15:25:30 adam-arch-laptop ModemManager[7776]: <msg> [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1c.6/0000:04:00.0': not supported by any plugin
Feb 22 15:25:30 adam-arch-laptop ModemManager[7776]: <msg> [base-manager] couldn't check support for device '/sys/devices/pci0000:00/0000:00:1f.6': not supported by any plugin
```

**Comment by binghamfluid** [comment]
the iosm drive can be used now for this modem. Just follow this easy steps:
1. git clone https://github.com/xmm7360/xmm7360-pci.git
2. add your apn in lte.sh: python3 $SCRIPT_DIR/../rpc/open_xdatachannel.py **--apn web.vodafone.de**
3. run sudo lte up
4. run sudo systemctl restart ModemManager
5. wait some time (10 to 20 sec.)
6. sudo mmcli -m 0

you should now connect to the mobile internet. To prove it just run:
ip addr show wwan0
ping -I wwan0 -c 4 8.8.8.8

OS: Linux Mint 22.1 Cinnamon 6.4.8 with Kernel 6.8.0.-71-generic

```
--------------------------------
  General  |                 path: /org/freedesktop/ModemManager1/Modem/0
           |            device id: cc9e0c13....
  --------------------------------
  Hardware |         manufacturer: Fibocom
           |                model: L850 LTE Module","L850
           |    firmware revision: 18500.5001.03.05.27.12
           |            supported: gsm-umts, lte
           |              current: gsm-umts, lte
           |         equipment id: 3597311...
  --------------------------------
  System   |               device: /sys/devices/pci0000:00/0000:00:1d.7/0000:6c:00.0
           |              physdev: /sys/devices/pci0000:00/0000:00:1d.7/0000:6c:00.0
           |              drivers: iosm
           |               plugin: Intel
           |         primary port: wwan0at1
           |                ports: wwan0 (net), wwan0at1 (at)
  --------------------------------
  Status   |       unlock retries: sim-pin (3), sim-puk (10), sim-pin2 (3), sim-puk2 (10)
           |                state: registered
           |          power state: on
           |          access tech: lte
           |       signal quality: 0% (recent)
  --------------------------------
  Modes    |            supported: allowed: 3g, 4g; preferred: none
           |              current: allowed: 3g, 4g; preferred: none
  --------------------------------
  IP       |            supported: ipv4, ipv6, ipv4v6
  --------------------------------
  3GPP     |                 imei: ******************
           |          operator id: 26202
           |        operator name: vodafone.de
           |         registration: home
           | packet service state: attached
  --------------------------------
  3GPP EPS | ue mode of operation: csps-2
  --------------------------------
  SIM      |     primary sim path: /org/freedesktop/ModemManager1/SIM/0
```
